v1
eesticham/blog-customizer pull request #1
Opened 2024-04-03 09:22 UTC by eesticham

Проектная работа 10

2024-04-03 19:48 UTC, olgalatkina requested changes
Добрый день!

**У вас получилась очень хорошая работа:**
1. Реализован весь функционал
2. Сайдбар закрывается по клику вне сайдбара
3. Типизированы все пропсы и события

**Но есть несколько моментов, которые надо поправить:**
- [ ] Для условного добавления стилей надо использовать библиотеку `clsx`.
- [ ] Каждый компонент сам должен отвечать за хранение и обработку своего состояния. Использовать подъем состояния в родительский компонент не имеет смысла для нашего приложения. Состояние формы нужно описать в самом компонент `ArticleParamsForm`, а не передавать его из `App`, т.к. это состояние описывает именно `ArticleParamsForm`. В состоянии `App` должны хранится только данные о текущем отображении статьи.
- [ ] Не стоит использовать `children` в этом проекте.
- [ ] По макету расстояние между элементами формы 50px. Нужно воспользоваться свойством `gap`.
- [ ] Форма не совсем совпадает с макетом: https://ru.paste.pics/849b5b24e64ddf7cc59ddf28737d3ff2 https://yadi.sk/i/gFkxg64V23fIzg

**Правки можно лучше остаются на ваше усмотрение:**
- [ ] Папка `hooks` должна находиться на одном уровне с папкой `components` , потому что компонент `ArticleParamsForm` не библиотечный и хук `useSidebarClose` будет общим для всего приложения. Кстати, ему лучше дать более подходящее начвание, ведь он универсальный и будет работать не только с сайдбаром. Его можно использовать в любом компоненте (попапе, меню и тд), которому нужно установить эти обработчики.
- [ ] Обычно корневой `index.tsx` держат максимально компактным. Стоит вынести компонент `App` в отдельный файл в папке `components/app/App.tsx`.
- [ ] Для одиночных селекторов не стоит использовать библиотеку `clsx`

Успешного рефакторинга!

2024-04-03 19:48 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.stories.tsx
> +		const [isOpened, setIsOpened] = useState(false);
_надо исправить:_
Верните "историю" к её предыдущему состоянию. Не вызываем здесь хуки реакта, не пишем логику работы обработчиков удалить. Если вам нужно передать в компонент обработчик и состояние, поправить "историю" можно так:
`<ArrowButton isOpen={true} onClick={() => {}} />`

2024-04-03 19:48 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +	handleClick: OnClick;
_можно лучше:_
`type OnClick` можно удалить а пропсы типизировать немного проще:
```
type ArrowButtonProps = {
	isOpened: boolean;
	handleClick: () => void;
};
```

2024-04-03 19:48 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +export const ArrowButton = (props: ArrowButtonProps) => {
_можно лучше:_
Обычно деструктуризацию "по месту" пишут, если пропсов немного, получится так:
`const ArrowButton = ({ isOpened, handleClick }: ArrowButtonProps) => {...}`

2024-04-03 19:48 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +	const refButton = useRef<HTMLDivElement | null>(null);
_надо исправить:_
Для того, чтобы менять стили по условию не понадобится ни `useRef`, ни `useEffect`. 
Чтобы добавлять стили по условию, достаточно воспользоваться библиотекой `clsx` (уже есть в проекте). Это требование есть в чек-листе: https://ru.paste.pics/89320309e689ee231362c674cd5bd828

Возможно, в этой статье вы найдёте больше информации: https://habr.com/ru/articles/649381/.

2024-04-03 19:48 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +		margin-top: 45px; // adjust the space between menus
_надо исправить:_
1. По макету расстояние между элементами формы 50px
2. У формы `display: flex`, чтобы корректно прописать расстояния между элементами формы нужно всего одно свойство прописать именно на форме.

2024-04-03 19:48 UTC, olgalatkina commented on src/index.tsx
> +	const [formState, setFormState] = useState(defaultArticleState);
_надо исправить:_
Компонент страницы не должен знать про состояние формы. Состояние формы надо перенести в компонент `ArticleParamsForm`. Туда же нужно перенести все обработчики.

2024-04-03 19:48 UTC, olgalatkina commented on src/index.tsx
>  			className={clsx(styles.main)}
_можно лучше:_
Для одиночных селекторов нет необходимости использовать библиотеку `clsx`. 
Замечание так же относится к компоненту `Article`

2024-04-03 19:48 UTC, olgalatkina commented on src/index.tsx
> +					'--font-family': pageState.fontFamilyOption.value,
_отлично:_
Замечательно! оптимальное решение.

2024-04-03 19:48 UTC, olgalatkina commented on src/index.tsx
> +				<Select
_надо исправить:_
Поля формы - это часть компонента `ArticleParamsForm`, отвечающего за настройки отображения статьи и не предусмотрено, что в форму будет передаваться разный набор полей ввода. Поэтому не имеет смысла в данном проекте передавать поля ввода в `ArticleParamsForm` как `children`, их нужно оставить просто в компоненте `ArticleParamsForm`

2024-04-03 19:48 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +				<form className={styles.form} onSubmit={onSubmit} onReset={onReset}>
_отлично:_
Отлично, что обработчик события `submit` на форме.

2024-04-05 12:26 UTC, eesticham commented on src/components/arrow-button/ArrowButton.stories.tsx
> +		const [isOpened, setIsOpened] = useState(false);
ваше предложение не работает, я просто закомментил код чтоб не мешал

2024-04-05 12:27 UTC, eesticham commented on src/components/arrow-button/ArrowButton.tsx
> +	const refButton = useRef<HTMLDivElement | null>(null);
действительно вышло коротко и лаконично

2024-04-05 12:27 UTC, eesticham commented on src/components/article-params-form/ArticleParamsForm.module.scss
> +		margin-top: 45px; // adjust the space between menus
действительно
что-то намудрил

2024-04-05 12:28 UTC, eesticham commented on src/index.tsx
> +	const [formState, setFormState] = useState(defaultArticleState);
сделано

2024-04-05 12:29 UTC, eesticham commented on src/index.tsx
>  			className={clsx(styles.main)}
проблема в том, что Article я даже не трогал
как раз таки наоборот - оттуда взял такой подход

можете взглянуть в мейн - так как раз ваши коллеги так и сделали

2024-04-05 12:30 UTC, eesticham commented on src/index.tsx
> +				<Select
сделано

2024-04-05 12:44 UTC, eesticham commented
5. Форма не совсем совпадает с макетом: https://ru.paste.pics/849b5b24e64ddf7cc59ddf28737d3ff2 https://yadi.sk/i/gFkxg64V23fIzg

Вот тут я попробовал исправить. Опять же шаблон проекта был заготовлен не нами. А тратить время на разбор чужого кода, исправления и тд, когда своя проектная работа горит - считаю нецелесообразной тратой времени.
Плюс добавлю - я попытался еще кнопки сделать как в макете. Но какое-то свойство мешало сменить цвет текста кнопки "Сброс". Попробовал разные подходы - ни один не сработал. В итоге решил оставить эту затею.


1. Папка hooks должна находиться на одном уровне с папкой components , потому что компонент ArticleParamsForm не библиотечный и хук useSidebarClose будет общим для всего приложения. Кстати, ему лучше дать более подходящее начвание, ведь он универсальный и будет работать не только с сайдбаром. Его можно использовать в любом компоненте (попапе, меню и тд), которому нужно установить эти обработчики.

Момент не совсем ясный ибо опять же делал по образу и подобию шаблона. Там в каждой папке подменю есть свои папки hooks. Поэтому я и создал папку hooks для ArticleParamsForm. Если уж и воплощать в жизнь Ваш комментарий, то придется переделать весь проект. Иначе будет странно. Поэтому я бы предложить Вам сначала разрешить вопрос с автором проекта и поменять изначальный шаблон для неопытных студентов. Дабы они (мы) учились, опираясь на то, что видим в работах, созданных более опытными специалистами. 


4. Для одиночных селекторов не стоит использовать библиотеку clsx

И снова вопрос к автору шаблона. Ибо такой подход взят из Article. А этот файл создан не мною. Я лишь увидел и посчитал, что "вот так делать надо. ведь шаблон заготовлен более опытным человеком". 


Вот такие соображения. Надеюсь Вы не сочтете их неуважительными. Я попытался изложить свои мысли и доводы по проекту. Прошу обратить внимание, что "Работа НЕ содержит вопросы или просьбы о помощи к ревьюеру."
Все мои вопрос больше из разряда риторических
Спасибо =)

2024-04-05 15:32 UTC, olgalatkina requested changes
Добрый день.

**Осталось всего пара моментов:**
1. В кастомном хуке обработчик, который отрабатывает на `onClose` должен сетить `false`
2. Для условного добавления стилей используем библиотеку `clsx`, а не useEffect

**Остальные замечания на ваше усмотрение:**
1. Нет необходимости создавать дополнительные функции обработчики, можно использовать просто функции сеттеры возвращаемые `useState`.
2. Использовать самозакрывающиеся теги, если нет контента.

Успешного рефакторинга!

2024-04-05 15:32 UTC, olgalatkina commented on src/components/app/App.tsx
> +  const handlePageStateUpdate = (newState: ArticleStateType) => {
_можно лучше:_
Нет необходимости создавать дополнительные функции обработчики если они сами по себе ничего не делают, можно использовать просто функции сеттеры возвращаемые `useState`. 

В React ссылка на функцию-сеттер, возвращаемую хуком `useState`, обычно является стабильной. Это означает, что она будет оставаться той же самой функцией при каждом рендере компонента. Если передать функцию-сеттер в пропсах дочернему компоненту, ссылка на эту функцию останется стабильной, если компонент перерисуется без изменений в пропсах.

В результате в JSX-разметке это будет выглядеть так:
```
<ArticleParamsForm onStateUpdate={setPageState} />
```

2024-04-05 15:32 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +					<div className={styles.divider}></div> {/* Элемент с линией */}
_можно лучше:_
Используем самозакрывающийся тег: `<div className={styles.divider} />`
Обычно линтер подсвечивает все сомнительные места. Можно внести исправления, нажав в контекстном меню `Quick Fix` или запустив в терминале команду из package.json `npm run format`

2024-04-05 15:32 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	useEffect(() => {
_надо исправить:_
Для условного добавления стилей лучше использовать билиотеку `clsx`.

2024-04-05 15:32 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +			className={clsx(styles.container, { [styles.container_open]: isOpened })}
_можно лучше:_
Этот стиль можно записать ещё короче: 
```
className={clsx(styles.container, isOpened && styles.container_open)}
```

2024-04-05 15:32 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +		onClose: toggleSidebar,
_надо исправить:_
Здесь всё же будет только закрытие формы, а не переключение: 
```
onClose: () => setIsOpened(false),
```

2024-04-05 15:32 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const handleChange = (name: keyof typeof formState, option: OptionType) => {
_можно лучше:_
`const handleChange = (name: keyof ArticleStateType, option: OptionType) => {...}`

2024-04-05 19:28 UTC, olgalatkina approved these changes
Работа принимается.

Надеюсь, вы исправите строчку с добавлением класса по условию. После рефакторинга там ошибка.

Удачи на следуюшей ПР.

2024-04-05 19:28 UTC, olgalatkina commented on src/components/article-params-form/ArticleParamsForm.tsx
> +			<aside className={clsx(styles.container, isOpened && styles.container_open)} ref={formRef} >
Супер! теперь всё правильно и никаких эффектов:)

2024-04-05 19:28 UTC, olgalatkina commented on src/components/arrow-button/ArrowButton.tsx
> +			className={clsx(styles.container, styles.container_open && isOpened )}
_надо исправить:_
Чуть внимательнее, пожалуйста🙏 После рефакторинга пропадает стрелка после открытия сайдбара..

2024-04-08 11:44 UTC, merged